# Generated by Django 2.0.3 on 2018-03-12 11:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品名')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('profile', models.CharField(max_length=100, verbose_name='简介')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('specs', models.CharField(max_length=20, verbose_name='规格')),
                ('on_click', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品类别')),
            ],
            options={
                'verbose_name': '商品类别信息',
                'verbose_name_plural': '商品类别信息',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='所属类别'),
        ),
    ]
