# Generated by Django 2.0.3 on 2018-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180312_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='zjm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='助记码'),
        ),
    ]
